#!/usr/bin/env python3
"""cargo-aiv v0 harness generator (prototype).

Parses a single-fn Rust file's SIGNATURE and emits a Kani proof harness:
  i32/u32/bool/...   -> let x: T = kani::any();
  Vec<iN>            -> bounded symbolic vec (len <= BOUND)
  Option<iN>         -> kani::any()
  anything else      -> UNSUPPORTED (reject the whole fn, gracefully)

This validates the signature->harness mapping. The product re-implements it in
Rust with `syn` (same logic). Property: panic-freedom + overflow, bounded.
"""
import glob
import json
import os
import re

BOUND = 3
UNWIND = 5
SCALARS = {"i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize", "bool"}


def parse_sig(code):
    m = re.search(r"fn\s+(\w+)\s*\(([^)]*)\)", code, re.S)
    name = m.group(1)
    params = []
    raw = m.group(2).strip()
    if raw:
        for p in raw.split(","):
            pm = re.match(r"(?:mut\s+)?(\w+)\s*:\s*(.+)", p.strip(), re.S)
            params.append((pm.group(1), re.sub(r"\s+", "", pm.group(2))))
    return name, params


def sym_input(pname, ptype):
    if ptype in SCALARS:
        return f"    let {pname}: {ptype} = kani::any();", True
    mv = re.match(r"Vec<(i8|i16|i32|i64|u8|u16|u32|u64)>$", ptype)
    if mv:
        return f"    let {pname}: Vec<{mv.group(1)}> = any_bounded_vec::<{mv.group(1)}>({BOUND});", True
    if re.match(r"Option<(i8|i16|i32|i64|u8|u16|u32|u64)>$", ptype):
        return f"    let {pname}: {ptype} = kani::any();", True
    return f"    // UNSUPPORTED param {pname}: {ptype}", False


def gen(code):
    name, params = parse_sig(code)
    lines, args, supported = [], [], True
    for pn, pt in params:
        line, ok = sym_input(pn, pt)
        lines.append(line)
        args.append(pn)
        supported &= ok
    harness = (f"#[kani::proof]\n#[kani::unwind({UNWIND})]\nfn verify_{name}() {{\n"
               + "\n".join(lines) + f"\n    let _ = {name}({', '.join(args)});\n}}\n")
    return name, supported, harness


HELPER = """// auto-generated by gen_harness.py — bounded symbolic Vec
fn any_bounded_vec<T: kani::Arbitrary>(bound: usize) -> Vec<T> {
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<T> = Vec::with_capacity(len);
    for _ in 0..len { v.push(kani::any()); }
    v
}
"""

if __name__ == "__main__":
    blocks, manifest = [HELPER], []
    for f in sorted(glob.glob("corpus/*.rs")):
        code = open(f).read()
        name, supported, harness = gen(code)
        manifest.append({"file": os.path.basename(f), "fn": name, "supported": supported})
        tag = "harness" if supported else "SKIPPED (unsupported type)"
        print(f"  {'✅' if supported else '⏭️ '} {name}: {tag}")
        if supported:
            blocks.append(code.rstrip() + "\n\n" + harness)
    os.makedirs("spike2/src", exist_ok=True)
    open("spike2/src/lib.rs", "w").write("\n".join(blocks))
    open("spike2/Cargo.toml", "w").write(
        '[package]\nname = "spike2"\nversion = "0.1.0"\nedition = "2021"\n[dependencies]\n')
    json.dump(manifest, open("gen_manifest.json", "w"), indent=2)
    sup = sum(1 for m in manifest if m["supported"])
    print(f"\n{sup}/{len(manifest)} functions auto-harnessed -> spike2/src/lib.rs "
          f"({len(manifest)-sup} correctly rejected as unsupported)")
