#!/usr/bin/env python3
"""cargo-vouch v0 harness generator (prototype).

Parses a single-fn Rust file's SIGNATURE and emits a Kani proof harness:
  i32/u32/bool/...   -> let x: T = kani::any();
  Vec<iN>            -> bounded symbolic vec (len <= BOUND)
  Option<iN>         -> kani::any()
  anything else      -> UNSUPPORTED (reject the whole fn, gracefully)

This validates the signature->harness mapping. The product re-implements it in
Rust with `syn` (same logic). Property: panic-freedom + overflow, bounded.
"""
import glob
import json
import os
import re

BOUND = 3
UNWIND = 5
SCALARS = {"i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize", "bool"}


def parse_sig(code):
    m = re.search(r"fn\s+(\w+)\s*\(([^)]*)\)", code, re.S)
    name = m.group(1)
    params = []
    raw = m.group(2).strip()
    if raw:
        for p in raw.split(","):
            pm = re.match(r"(?:mut\s+)?(\w+)\s*:\s*(.+)", p.strip(), re.S)
            params.append((pm.group(1), re.sub(r"\s+", "", pm.group(2))))
    return name, params


# In realistic mode, scalar inputs are constrained to a normal range and Vec
# elements are drawn from that range — so a panic that STILL occurs is reachable
# on ordinary input (a genuine BUG), while a panic that disappears was only an
# unguarded overflow at i32::MAX/MIN (downgrade, don't cry wolf).
RANGE = 1000


def sym_input(pname, ptype, realistic):
    if ptype in SCALARS:
        base = f"    let {pname}: {ptype} = kani::any();"
        if realistic and ptype.startswith("i"):
            base += f"\n    kani::assume({pname} >= -{RANGE} && {pname} <= {RANGE});"
        elif realistic and ptype.startswith("u"):
            base += f"\n    kani::assume({pname} <= {RANGE});"
        return base, True
    mv = re.match(r"Vec<(i8|i16|i32|i64|u8|u16|u32|u64)>$", ptype)
    if mv:
        et = mv.group(1)
        if realistic and et == "i32":
            return f"    let {pname}: Vec<i32> = any_bounded_vec_ranged({BOUND});", True
        return f"    let {pname}: Vec<{et}> = any_bounded_vec::<{et}>({BOUND});", True
    if re.match(r"Option<(i8|i16|i32|i64|u8|u16|u32|u64)>$", ptype):
        return f"    let {pname}: {ptype} = kani::any();", True
    return f"    // UNSUPPORTED param {pname}: {ptype}", False


def gen(code, realistic=False):
    name, params = parse_sig(code)
    lines, args, supported = [], [], True
    for pn, pt in params:
        line, ok = sym_input(pn, pt, realistic)
        lines.append(line)
        args.append(pn)
        supported &= ok
    harness = (f"#[kani::proof]\n#[kani::unwind({UNWIND})]\nfn verify_{name}() {{\n"
               + "\n".join(lines) + f"\n    let _ = {name}({', '.join(args)});\n}}\n")
    return name, supported, harness


HELPER = """// auto-generated by gen_harness.py — bounded symbolic Vec helpers
fn any_bounded_vec<T: kani::Arbitrary>(bound: usize) -> Vec<T> {
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<T> = Vec::with_capacity(len);
    for _ in 0..len { v.push(kani::any()); }
    v
}
fn any_bounded_vec_ranged(bound: usize) -> Vec<i32> {
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<i32> = Vec::with_capacity(len);
    for _ in 0..len { let x: i32 = kani::any(); kani::assume(x >= -1000 && x <= 1000); v.push(x); }
    v
}
"""


def generate(outdir, realistic, corpus="corpus/*.rs"):
    """Generate a Kani crate at `outdir`. Returns [(fn, supported)]."""
    blocks, manifest, pkg = [HELPER], [], os.path.basename(outdir)
    for f in sorted(glob.glob(corpus)):
        code = open(f).read()
        name, supported, harness = gen(code, realistic)
        manifest.append((name, supported))
        if supported:
            blocks.append(code.rstrip() + "\n\n" + harness)
    os.makedirs(f"{outdir}/src", exist_ok=True)
    open(f"{outdir}/src/lib.rs", "w").write("\n".join(blocks))
    open(f"{outdir}/Cargo.toml", "w").write(
        f'[package]\nname = "{pkg}"\nversion = "0.1.0"\nedition = "2021"\n[dependencies]\n')
    return manifest


if __name__ == "__main__":
    m = generate("spike2", realistic=False)
    for name, ok in m:
        print(f"  {'✅' if ok else '⏭️ '} {name}: {'harness' if ok else 'SKIPPED (unsupported)'}")
    sup = sum(1 for _, ok in m if ok)
    print(f"\n{sup}/{len(m)} auto-harnessed -> spike2/ ({len(m)-sup} rejected as unsupported)")
