// auto-generated by cargo-vouch
fn any_bounded_vec<T: kani::Arbitrary>(bound: usize) -> Vec<T> {
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<T> = Vec::with_capacity(len);
    for _ in 0..len { v.push(kani::any()); }
    v
}

fn find_max(numbers: Vec<i32>) -> i32 {
    *numbers.iter().max().unwrap()
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_find_max() {
    let numbers: Vec<i32> = any_bounded_vec::<i32>(3);
    let _ = find_max(numbers);
}
