// auto-generated by gen_harness.py — bounded symbolic Vec helpers
fn any_bounded_vec<T: kani::Arbitrary>(bound: usize) -> Vec<T> {
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<T> = Vec::with_capacity(len);
    for _ in 0..len { v.push(kani::any()); }
    v
}
fn any_bounded_vec_ranged(bound: usize) -> Vec<i32> {
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<i32> = Vec::with_capacity(len);
    for _ in 0..len { let x: i32 = kani::any(); kani::assume(x >= -1000 && x <= 1000); v.push(x); }
    v
}

fn sum_vec(numbers: Vec<i32>) -> i32 {
    numbers.iter().sum()
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_sum_vec() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = sum_vec(numbers);
}

fn get_third(items: Vec<i32>) -> Option<i32> {
    if items.len() >= 3 {
        Some(items[2])
    } else {
        None
    }
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_get_third() {
    let items: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = get_third(items);
}

fn double_first(numbers: Vec<i32>) -> i32 {
    numbers.iter().next().unwrap() * 2
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_double_first() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = double_first(numbers);
}

fn divide(a: i32, b: i32) -> i32 {
    a / b
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_divide() {
    let a: i32 = kani::any();
    kani::assume(a >= -1000 && a <= 1000);
    let b: i32 = kani::any();
    kani::assume(b >= -1000 && b <= 1000);
    let _ = divide(a, b);
}

fn increment_all(numbers: Vec<i32>) -> Vec<i32> {
    numbers.into_iter().map(|x| x + 1).collect()
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_increment_all() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = increment_all(numbers);
}

fn find_max(numbers: Vec<i32>) -> i32 {
    *numbers.iter().max().unwrap()
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_find_max() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = find_max(numbers);
}

fn prepend_zero(mut numbers: Vec<i32>) -> Vec<i32> {
    numbers.insert(0, 0);
    numbers
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_prepend_zero() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = prepend_zero(numbers);
}

fn square_sum(numbers: Vec<i32>) -> i32 {
    numbers.iter().map(|x| x * x).sum()
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_square_sum() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = square_sum(numbers);
}

fn remove_last(mut numbers: Vec<i32>) -> Vec<i32> {
    numbers.pop();
    numbers
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_remove_last() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = remove_last(numbers);
}

fn subtract_min(numbers: Vec<i32>) -> i32 {
    let min = *numbers.iter().min().unwrap();
    numbers.iter().map(|x| x - min).sum()
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_subtract_min() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = subtract_min(numbers);
}

fn average(numbers: Vec<i32>) -> f64 {
    let sum: i32 = numbers.iter().sum();
    sum as f64 / numbers.len() as f64
}

#[kani::proof]
#[kani::unwind(5)]
fn verify_average() {
    let numbers: Vec<i32> = any_bounded_vec_ranged(3);
    let _ = average(numbers);
}
