//! cargo-aiv — prove AI-generated Rust is panic-free (don't just test it).
//!
//! Parses a single-fn `.rs` with `syn`, auto-generates a Kani proof harness,
//! runs bounded model checking in TWO modes (strict + realistic), and reports:
//!   🔴 BUG        panic reachable on ordinary input — fix it
//!   🟡 UNGUARDED  overflow only at i32::MAX/MIN — add a guard (not a false alarm)
//!   ✅ VERIFIED   panic-free for Vec≤3, |val|≤1000
//!
//!   cargo-aiv <file.rs>          # verify (default)
//!   cargo-aiv --emit <file.rs>   # just print the generated harness

use quote::quote;
use std::collections::BTreeMap;
use std::fs;
use std::io::Read;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::thread;
use std::time::{Duration, Instant};

const BOUND: usize = 3;
const UNWIND: u32 = 5;
const RANGE: i64 = 1000;
/// Per-mode wall-clock cap. Kani can run for minutes on adapter-heavy functions;
/// past this we report ⏱️ INCONCLUSIVE rather than hang a CI job forever.
const TIMEOUT_SECS: u64 = 120;
const SCALARS: &[&str] = &[
    "i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize", "bool",
];
const G: &str = "\x1b[32m";
const R: &str = "\x1b[31m";
const Y: &str = "\x1b[33m";
const B: &str = "\x1b[1m";
const DIM: &str = "\x1b[2m";
const X: &str = "\x1b[0m";

fn helper() -> String {
    format!(
        r#"// auto-generated by cargo-aiv
fn any_bounded_vec<T: kani::Arbitrary>(bound: usize) -> Vec<T> {{
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<T> = Vec::with_capacity(len);
    for _ in 0..len {{ v.push(kani::any()); }}
    v
}}
fn any_bounded_vec_ranged(bound: usize) -> Vec<i32> {{
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<i32> = Vec::with_capacity(len);
    for _ in 0..len {{ let x: i32 = kani::any(); kani::assume(x >= -{RANGE} && x <= {RANGE}); v.push(x); }}
    v
}}"#
    )
}

fn path_head(ty: &syn::Type) -> Option<(String, Vec<syn::Type>)> {
    if let syn::Type::Path(tp) = ty {
        if let Some(seg) = tp.path.segments.last() {
            let mut args = Vec::new();
            if let syn::PathArguments::AngleBracketed(ab) = &seg.arguments {
                for a in &ab.args {
                    if let syn::GenericArgument::Type(t) = a {
                        args.push(t.clone());
                    }
                }
            }
            return Some((seg.ident.to_string(), args));
        }
    }
    None
}

fn scalar_int(ty: &syn::Type) -> Option<String> {
    let (base, args) = path_head(ty)?;
    (args.is_empty() && SCALARS.contains(&base.as_str())).then_some(base)
}

/// A bounded symbolic `Vec<et>` binding line. `mutable` makes it `let mut`.
fn vec_binding(name: &str, et: &str, realistic: bool, mutable: bool) -> String {
    let m = if mutable { "mut " } else { "" };
    if realistic && et == "i32" {
        format!("    let {m}{name}: Vec<i32> = any_bounded_vec_ranged({BOUND});")
    } else {
        format!("    let {m}{name}: Vec<{et}> = any_bounded_vec::<{et}>({BOUND});")
    }
}

/// Map a parameter to (binding line(s), argument expression at the call site).
/// The arg expr differs from the name for by-reference params (`&v`, `&mut v`).
fn map_input(name: &str, ty: &syn::Type, realistic: bool) -> Option<(String, String)> {
    if let Some(s) = scalar_int(ty) {
        let mut line = format!("    let {name}: {s} = kani::any();");
        if realistic && s.starts_with('i') {
            line += &format!("\n    kani::assume({name} >= -{RANGE} && {name} <= {RANGE});");
        } else if realistic && s.starts_with('u') {
            line += &format!("\n    kani::assume({name} <= {RANGE});");
        }
        return Some((line, name.to_string()));
    }
    // &[int] / &mut [int] — bind a symbolic Vec and pass it by reference (a `&Vec`
    // coerces to `&[T]`). Covers slice params, extremely common in AI Rust.
    if let syn::Type::Reference(r) = ty {
        if let syn::Type::Slice(sl) = &*r.elem {
            let et = scalar_int(&sl.elem)?;
            let mutable = r.mutability.is_some();
            let arg = if mutable { format!("&mut {name}") } else { format!("&{name}") };
            return Some((vec_binding(name, &et, realistic, mutable), arg));
        }
        // &Vec<int> / &mut Vec<int>
        if let Some(("Vec", inner)) = path_head(&r.elem).as_ref().map(|(b, a)| (b.as_str(), a)) {
            let et = scalar_int(inner.first()?)?;
            let mutable = r.mutability.is_some();
            let arg = if mutable { format!("&mut {name}") } else { format!("&{name}") };
            return Some((vec_binding(name, &et, realistic, mutable), arg));
        }
    }
    let (base, args) = path_head(ty)?;
    match (base.as_str(), args.as_slice()) {
        ("Vec", [inner]) => {
            let et = scalar_int(inner)?;
            Some((vec_binding(name, &et, realistic, false), name.to_string()))
        }
        ("Option", [inner]) => {
            scalar_int(inner)?;
            let tystr = quote!(#ty).to_string().replace(' ', "");
            Some((format!("    let {name}: {tystr} = kani::any();"), name.to_string()))
        }
        _ => None,
    }
}

/// Build the full lib.rs (helper + fn + harness) for one mode. Err(msg) if unsupported.
/// `postcond`, if set, is a boolean Rust expr over `result` (and the input names)
/// that becomes a proof obligation instead of the default panic-freedom check.
fn build(src: &str, realistic: bool, postcond: Option<&str>) -> Result<(String, String), String> {
    let file = syn::parse_file(src).map_err(|e| format!("parse error: {e}"))?;
    let func = file
        .items
        .iter()
        .find_map(|it| if let syn::Item::Fn(f) = it { Some(f) } else { None })
        .ok_or("no top-level function found")?;
    let name = func.sig.ident.to_string();
    let mut inputs = Vec::new();
    let mut args = Vec::new();
    for arg in &func.sig.inputs {
        if let syn::FnArg::Typed(pt) = arg {
            let pname = match &*pt.pat {
                syn::Pat::Ident(pi) => pi.ident.to_string(),
                _ => return Err(format!("unsupported parameter pattern in `{name}`")),
            };
            let (line, arg_expr) = map_input(&pname, &pt.ty, realistic).ok_or_else(|| {
                format!("`{name}` param `{pname}: {}` unsupported (v0: scalar ints, Vec<int>, Option<int>, &[int])", quote!(#pt).to_string())
            })?;
            inputs.push(line);
            args.push(arg_expr);
        }
    }
    let call = args.join(", ");
    let tail = match postcond {
        Some(expr) => format!(
            "    let result = {name}({call});\n    kani::assert({expr}, \"aiv postcondition\");\n    let _ = &result;"
        ),
        None => format!("    let _ = {name}({call});"),
    };
    let lib = format!(
        "{}\n\n{}\n\n#[kani::proof]\n#[kani::unwind({UNWIND})]\nfn verify_{name}() {{\n{}\n{}\n}}\n",
        helper(),
        src.trim(),
        inputs.join("\n"),
        tail,
    );
    Ok((name, lib))
}

/// Run `cargo kani` in `dir`, draining stdout+stderr on threads (so a full pipe
/// buffer can't deadlock the child) and killing it past `TIMEOUT_SECS`.
/// Returns None if the run timed out or couldn't start.
fn kani_output(dir: &PathBuf) -> Option<String> {
    let mut child = Command::new("cargo")
        .arg("kani")
        .current_dir(dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .ok()?;
    let mut so = child.stdout.take()?;
    let mut se = child.stderr.take()?;
    let ho = thread::spawn(move || {
        let mut s = String::new();
        so.read_to_string(&mut s).ok();
        s
    });
    let he = thread::spawn(move || {
        let mut s = String::new();
        se.read_to_string(&mut s).ok();
        s
    });
    let start = Instant::now();
    loop {
        match child.try_wait() {
            Ok(Some(_)) => break,
            Ok(None) => {
                if start.elapsed() > Duration::from_secs(TIMEOUT_SECS) {
                    let _ = child.kill();
                    let _ = child.wait();
                    return None; // timed out — pipes hit EOF, reader threads unblock
                }
                thread::sleep(Duration::from_millis(200));
            }
            Err(_) => return None,
        }
    }
    Some(ho.join().unwrap_or_default() + &he.join().unwrap_or_default())
}

fn run_kani(dir: &PathBuf, name: &str, lib: &str) -> Option<BTreeMap<String, (bool, Vec<String>)>> {
    fs::create_dir_all(dir.join("src")).ok();
    fs::write(
        dir.join("Cargo.toml"),
        format!("[package]\nname = \"aiv_{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\n"),
    )
    .ok();
    fs::write(dir.join("src/lib.rs"), lib).ok();
    let text = kani_output(dir)?;
    let mut res = BTreeMap::new();
    let mut cur = String::new();
    for ln in text.lines() {
        if let Some(i) = ln.find("Checking harness verify_") {
            cur = ln[i + "Checking harness verify_".len()..]
                .split(['.', ' '])
                .next()
                .unwrap_or("")
                .to_string();
            res.insert(cur.clone(), (false, Vec::new()));
        } else if !cur.is_empty() && ln.contains("Failed Checks:") {
            if let Some(e) = res.get_mut(&cur) {
                e.1.push(ln.split("Failed Checks:").nth(1).unwrap_or("").trim().to_string());
            }
        } else if !cur.is_empty() && ln.contains("VERIFICATION:-") {
            if let Some(e) = res.get_mut(&cur) {
                e.0 = ln.contains("FAILED");
            }
        }
    }
    Some(res)
}

/// Re-run a failing harness with concrete playback to extract the triggering input.
/// Returns (assertion message, symbolic input values in order).
fn counterexample(dir: &PathBuf, name: &str) -> Option<(String, Vec<String>)> {
    let out = Command::new("cargo")
        .args([
            "kani",
            "--harness",
            &format!("verify_{name}"),
            "-Z",
            "concrete-playback",
            "--concrete-playback=print",
        ])
        .current_dir(dir)
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&out.stdout).to_string() + &String::from_utf8_lossy(&out.stderr);
    parse_playback(&text)
}

/// Parse Kani `--concrete-playback=print` output into (assertion message, input
/// values in order). Pure so it can be unit-tested against captured Kani output.
///
/// Kani prints one `concrete_vals` block per failing check; each is a complete,
/// independent witness. We keep only the FIRST — merging tokens across blocks
/// produces a meaningless list (e.g. mixing a postcondition witness with a
/// separate panic witness).
fn parse_playback(text: &str) -> Option<(String, Vec<String>)> {
    let (mut assertion, mut vals, mut in_block, mut done) =
        (String::new(), Vec::new(), false, false);
    for ln in text.lines() {
        if assertion.is_empty() {
            if let Some(i) = ln.find("Check for `assertion`: \"") {
                assertion = ln[i + "Check for `assertion`: \"".len()..].trim_end_matches('"').to_string();
            }
        }
        if !done && ln.contains("let concrete_vals") {
            in_block = true;
            continue;
        }
        if in_block {
            let t = ln.trim();
            if t.starts_with("//") {
                vals.push(t.trim_start_matches("//").trim().to_string());
            }
            if t.contains("];") {
                in_block = false;
                done = true; // first block captured — ignore any further blocks
            }
        }
    }
    (!assertion.is_empty() || !vals.is_empty()).then_some((assertion, vals))
}

#[cfg(test)]
mod tests {
    use super::{interpret_val, parse_playback};

    // Two failing checks → two concrete_vals blocks. We must keep only the first
    // witness, not merge tokens across blocks (the find_max --prove regression).
    #[test]
    fn playback_keeps_only_first_witness_block() {
        let kani = r#"
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 1ul
        vec![1, 0, 0, 0, 0, 0, 0, 0],
        // -1
        vec![255, 255, 255, 255],
    ];
    kani::concrete_playback_run(concrete_vals, verify_find_max);
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 0ul
        vec![0, 0, 0, 0, 0, 0, 0, 0],
    ];
"#;
        let (_, vals) = parse_playback(kani).unwrap();
        assert_eq!(vals, vec!["1ul", "-1"]); // NOT ["1ul","-1","0ul"]
    }

    // One failing check with two params → one block holding all param values.
    // The first-block rule must NOT truncate this (the dot_index case).
    #[test]
    fn playback_keeps_all_params_in_one_block() {
        let kani = r#"
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 1ul
        vec![1, 0, 0, 0, 0, 0, 0, 0],
        // -1
        vec![255, 255, 255, 255],
        // 0ul
        vec![0, 0, 0, 0, 0, 0, 0, 0],
    ];
"#;
        let (_, vals) = parse_playback(kani).unwrap();
        assert_eq!(vals, vec!["1ul", "-1", "0ul"]);
    }

    #[test]
    fn playback_captures_assertion_message() {
        let kani = "Check for `assertion`: \"attempt to add with overflow\"\n    let concrete_vals: Vec<Vec<u8>> = vec![\n        // 5i32\n    ];";
        let (msg, vals) = parse_playback(kani).unwrap();
        assert_eq!(msg, "attempt to add with overflow");
        assert_eq!(vals, vec!["5i32"]);
    }

    #[test]
    fn playback_none_when_no_block() {
        assert!(parse_playback("VERIFICATION:- SUCCESSFUL\n").is_none());
    }

    #[test]
    fn usize_reads_as_vector_length() {
        assert_eq!(interpret_val("0ul"), "0 (usize → empty vector)");
        assert_eq!(interpret_val("1ul"), "1 (usize → 1-element vector)");
        assert_eq!(interpret_val("3ul"), "3 (usize → vector of length 3)");
    }
    #[test]
    fn names_overflow_sentinels() {
        assert_eq!(interpret_val("-2147483648i32"), "-2147483648 (i32::MIN)");
        assert_eq!(interpret_val("2147483647i32"), "2147483647 (i32::MAX)");
        assert_eq!(interpret_val("127i8"), "127 (i8::MAX)");
        assert_eq!(interpret_val("255u8"), "255 (u8::MAX)");
    }
    #[test]
    fn ordinary_values_pass_through_without_suffix() {
        assert_eq!(interpret_val("5i32"), "5");
        assert_eq!(interpret_val("-3i64"), "-3");
        assert_eq!(interpret_val("42"), "42");
        assert_eq!(interpret_val("true"), "true");
        // a non-extreme value that shares a width but isn't the sentinel
        assert_eq!(interpret_val("100i8"), "100");
    }
}

/// Turn a raw Kani concrete value token (`"0ul"`, `"-2147483648i32"`, `"true"`)
/// into something a human reads at a glance. Conservative: only annotates values
/// it can identify unambiguously (usize length, min/max sentinels); otherwise
/// strips the type suffix and passes the number through.
fn interpret_val(tok: &str) -> String {
    let t = tok.trim();
    if t == "true" || t == "false" {
        return t.to_string();
    }
    // split "-123" core from "i32"/"ul"/... suffix
    let split = t.find(|c: char| c.is_ascii_alphabetic() && c != '-');
    let (core, suffix) = match split {
        Some(i) => (&t[..i], &t[i..]),
        None => (t, ""),
    };
    // usize only ever appears as a symbolic Vec/slice length in our harnesses
    if suffix == "ul" || suffix == "usize" {
        return match core {
            "0" => "0 (usize → empty vector)".to_string(),
            "1" => "1 (usize → 1-element vector)".to_string(),
            n => format!("{n} (usize → vector of length {n})"),
        };
    }
    // name overflow sentinels (min/max for the signed/unsigned width)
    let sentinel = match (suffix, core) {
        ("i8", "-128") => Some("i8::MIN"),
        ("i8", "127") => Some("i8::MAX"),
        ("i16", "-32768") => Some("i16::MIN"),
        ("i16", "32767") => Some("i16::MAX"),
        ("i32", "-2147483648") => Some("i32::MIN"),
        ("i32", "2147483647") => Some("i32::MAX"),
        ("i64" | "isize", "-9223372036854775808") => Some("i64::MIN"),
        ("i64" | "isize", "9223372036854775807") => Some("i64::MAX"),
        ("u8", "255") => Some("u8::MAX"),
        ("u16", "65535") => Some("u16::MAX"),
        ("u32", "4294967295") => Some("u32::MAX"),
        _ => None,
    };
    match sentinel {
        Some(name) => format!("{core} ({name})"),
        None => core.to_string(),
    }
}

enum Verdict {
    Verified,
    Bug(Vec<String>, Vec<String>), // failed checks, counterexample value tokens
    Unguarded(Vec<String>),        // overflow only at extremes
    Inconclusive,
    Unsupported(String),
}

/// Classify one function (panic-freedom mode): strict + realistic, then dual-mode
/// classify. Pure of printing — used by both single-file and batch paths. `slot`
/// namespaces the temp dir so parallel batch workers can't collide (even on
/// same-named functions across files).
fn verify_one(src: &str, slot: usize) -> (String, Verdict) {
    let (name, strict_lib) = match build(src, false, None) {
        Ok(v) => v,
        Err(e) => return (String::new(), Verdict::Unsupported(e)),
    };
    let real_lib = build(src, true, None).unwrap().1;
    let base = std::env::temp_dir().join(format!("cargo-aiv-{name}-{slot}"));
    let (strict, real) = match (
        run_kani(&base.join("strict"), &name, &strict_lib),
        run_kani(&base.join("realistic"), &name, &real_lib),
    ) {
        (Some(s), Some(r)) => (s, r),
        _ => return (name, Verdict::Inconclusive),
    };
    let s = strict.get(&name).cloned().unwrap_or((false, vec![]));
    let r = real.get(&name).cloned().unwrap_or((false, vec![]));
    let verdict = if !s.0 {
        Verdict::Verified
    } else if r.0 {
        let vals = counterexample(&base.join("realistic"), &name)
            .map(|(_, v)| v)
            .unwrap_or_default();
        Verdict::Bug(r.1, vals)
    } else {
        Verdict::Unguarded(s.1)
    };
    (name, verdict)
}

/// Exit code convention shared by single-file and batch: BUG → 1, else 0
/// (INCONCLUSIVE stays 2 in single-file for back-compat).
fn verdict_code(v: &Verdict) -> i32 {
    match v {
        Verdict::Bug(..) => 1,
        Verdict::Inconclusive => 2,
        Verdict::Unsupported(_) => 1,
        _ => 0,
    }
}

/// Detailed single-file report. Returns the process exit code.
fn print_detailed(name: &str, v: &Verdict) -> i32 {
    println!();
    match v {
        Verdict::Verified => {
            println!("{G}{B}✅ VERIFIED{X}  `{name}` — panic-free for Vec≤{BOUND}, |val|≤{RANGE}.");
        }
        Verdict::Bug(checks, vals) => {
            println!("{R}{B}🔴 BUG{X}  `{name}` — panic reachable on ordinary input:");
            for c in checks {
                println!("     {R}• {c}{X}");
            }
            if !vals.is_empty() {
                let pretty: Vec<String> = vals.iter().map(|v| interpret_val(v)).collect();
                println!("     {DIM}reachable with input(s), in order: {}{X}", pretty.join(", "));
            }
        }
        Verdict::Unguarded(checks) => {
            println!("{Y}{B}🟡 UNGUARDED{X}  `{name}` — safe on normal input, but overflows at i32::MAX/MIN:");
            for c in checks {
                println!("     {Y}• {c}{X}");
            }
            println!("     {DIM}add a bounds guard or use checked_/saturating_ arithmetic.{X}");
        }
        Verdict::Inconclusive => {
            println!("{Y}{B}⏱️  INCONCLUSIVE{X}  `{name}` — didn't finish within {TIMEOUT_SECS}s/mode.");
            println!("     {DIM}too complex to prove at the current bounds (Vec≤{BOUND}, unwind {UNWIND}). Not a pass — not a bug.{X}");
        }
        Verdict::Unsupported(e) => {
            println!("{Y}⏭  cargo-aiv: {e}{X}");
        }
    }
    verdict_code(v)
}

/// Batch mode: verify every file in parallel (bounded workers), print a compact
/// table in input order, exit 1 if any BUG. Parallelism is what makes verifying a
/// whole crate tractable — sequential Kani runs over N functions don't scale.
fn batch(files: &[String]) -> i32 {
    let tag = |v: &Verdict| match v {
        Verdict::Verified => format!("{G}✅ VERIFIED{X}"),
        Verdict::Bug(..) => format!("{R}🔴 BUG{X}"),
        Verdict::Unguarded(_) => format!("{Y}🟡 UNGUARDED{X}"),
        Verdict::Inconclusive => format!("{Y}⏱️  INCONCLUSIVE{X}"),
        Verdict::Unsupported(_) => format!("{DIM}⏭  unsupported{X}"),
    };
    // Kani/CBMC is CPU- and memory-heavy and already multi-threaded, so each run
    // wants most of the machine. Over-parallelizing starves individual runs past
    // their timeout → FALSE ⏱️ INCONCLUSIVE. Keep concurrency low: ~cores/4, ≤3.
    let workers = std::thread::available_parallelism()
        .map(|n| (n.get() / 4).max(1))
        .unwrap_or(2)
        .clamp(1, 3)
        .min(files.len().max(1));
    println!(
        "{DIM}cargo-aiv batch — {} file(s), {workers} workers, ≤{TIMEOUT_SECS}s/mode each{X}\n",
        files.len()
    );
    let next = std::sync::atomic::AtomicUsize::new(0);
    let results: std::sync::Mutex<Vec<(usize, String, Verdict)>> =
        std::sync::Mutex::new(Vec::new());
    thread::scope(|scope| {
        for _ in 0..workers {
            scope.spawn(|| loop {
                let i = next.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                if i >= files.len() {
                    break;
                }
                let f = &files[i];
                let (label, v) = match fs::read_to_string(f) {
                    Ok(src) => {
                        let (name, v) = verify_one(&src, i);
                        (if name.is_empty() { f.clone() } else { name }, v)
                    }
                    Err(e) => (f.clone(), Verdict::Unsupported(e.to_string())),
                };
                results.lock().unwrap().push((i, label, v));
            });
        }
    });
    let mut out = results.into_inner().unwrap();
    out.sort_by_key(|(i, _, _)| *i);
    let (mut bugs, mut ung, mut ver, mut other) = (0, 0, 0, 0);
    for (_, label, v) in &out {
        match v {
            Verdict::Bug(..) => bugs += 1,
            Verdict::Unguarded(_) => ung += 1,
            Verdict::Verified => ver += 1,
            _ => other += 1,
        }
        let detail = match v {
            Verdict::Bug(_, vals) if !vals.is_empty() => {
                let p: Vec<String> = vals.iter().map(|x| interpret_val(x)).collect();
                format!("  {DIM}← {}{X}", p.join(", "))
            }
            _ => String::new(),
        };
        println!("  {:<22} {}{}", label, tag(v), detail);
    }
    println!(
        "\n{DIM}────{X}\n{R}{bugs} BUG{X} · {Y}{ung} UNGUARDED{X} · {G}{ver} VERIFIED{X} · {other} other"
    );
    i32::from(bugs > 0)
}

fn main() {
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    if args.first().map(|s| s.as_str()) == Some("aiv") {
        args.remove(0); // invoked as `cargo aiv ...`
    }
    let emit = args.iter().any(|a| a == "--emit");
    // --prove '<expr>' consumes the following arg as the postcondition
    let mut prove: Option<String> = None;
    if let Some(i) = args.iter().position(|a| a == "--prove") {
        match args.get(i + 1).cloned() {
            Some(expr) => {
                prove = Some(expr);
                args.drain(i..=i + 1);
            }
            None => {
                eprintln!("usage: cargo-aiv --prove '<bool expr over result/inputs>' <file.rs>");
                std::process::exit(2);
            }
        }
    }
    let files: Vec<String> = args.iter().filter(|a| !a.starts_with("--")).cloned().collect();
    if files.is_empty() {
        eprintln!("usage: cargo-aiv [--emit] [--prove '<expr>'] <file.rs>...");
        std::process::exit(2);
    }

    // Batch mode: 2+ files → summary table, one exit code (only with plain verify).
    if files.len() > 1 && !emit && prove.is_none() {
        std::process::exit(batch(&files));
    }

    let file = files[0].clone();
    let src = fs::read_to_string(&file).unwrap_or_else(|e| {
        eprintln!("cannot read {file}: {e}");
        std::process::exit(2);
    });

    if emit {
        match build(&src, prove.is_some(), prove.as_deref()) {
            Ok((_, lib)) => println!("{lib}"),
            Err(e) => {
                eprintln!("cargo-aiv: {e}");
                std::process::exit(1);
            }
        }
        return;
    }

    // --prove: check a postcondition over the return value (realistic bounds).
    if let Some(expr) = prove {
        let (name, lib) = match build(&src, true, Some(&expr)) {
            Ok(v) => v,
            Err(e) => {
                println!("{Y}⏭  cargo-aiv: {e}{X}");
                std::process::exit(1);
            }
        };
        println!("{DIM}proving `{name}`: {B}{expr}{X}{DIM}  (all inputs, |val|≤{RANGE}, Vec≤{BOUND})…{X}");
        let dir = std::env::temp_dir().join(format!("cargo-aiv-{name}-prove"));
        let res = match run_kani(&dir, &name, &lib) {
            Some(r) => r,
            None => {
                println!("\n{Y}{B}⏱️  INCONCLUSIVE{X}  `{name}` — didn't finish within {TIMEOUT_SECS}s.");
                std::process::exit(2);
            }
        };
        let v = res.get(&name).cloned().unwrap_or((false, vec![]));
        println!();
        if !v.0 {
            println!("{G}{B}✅ PROVEN{X}  `{name}` — {B}{expr}{X} holds for all inputs in bounds.");
            std::process::exit(0);
        }
        println!("{R}{B}🔴 VIOLATED{X}  `{name}` — {B}{expr}{X} can be false (or the fn panics first):");
        for c in &v.1 {
            println!("     {R}• {c}{X}");
        }
        if let Some((_a, vals)) = counterexample(&dir, &name) {
            if !vals.is_empty() {
                let pretty: Vec<String> = vals.iter().map(|v| interpret_val(v)).collect();
                println!("     {DIM}counterexample input(s), in order: {}{X}", pretty.join(", "));
            }
        }
        std::process::exit(1);
    }

    // Single-file verify: strict + realistic, dual-mode classify, detailed report.
    let peek = build(&src, false, None).map(|(n, _)| n).unwrap_or_default();
    if !peek.is_empty() {
        println!("{DIM}verifying `{peek}` (strict + realistic bounded model checking, ≤{TIMEOUT_SECS}s/mode)…{X}");
    }
    let (name, verdict) = verify_one(&src, 0);
    let label = if name.is_empty() { file } else { name };
    std::process::exit(print_detailed(&label, &verdict));
}
