//! cargo-aiv — prove AI-generated Rust is panic-free (don't just test it).
//!
//! Parses a `.rs` file with `syn`, auto-generates a Kani proof harness for every
//! top-level function, runs bounded model checking in TWO modes (strict +
//! realistic), and reports per function:
//!   🔴 BUG          panic reachable on ordinary input — fix it
//!   🟡 UNGUARDED    overflow only at i32::MAX/MIN — add a guard (not a false alarm)
//!   ✅ VERIFIED     panic-free within bounds
//!   ⏱️  INCONCLUSIVE didn't finish within the per-mode timeout
//!
//!   cargo-aiv <file.rs>...            verify one file, or many (parallel batch)
//!   cargo-aiv --prove '<expr>' <file> prove a postcondition over `result`/inputs
//!   cargo-aiv --emit <file.rs>        print the generated harness, don't run
//!   cargo-aiv --json <file.rs>...     machine-readable results
//!   cargo-aiv --selftest              check the Kani wiring is trustworthy
//!   cargo-aiv --bound N / --unwind N  tune the BMC depth

use quote::quote;
use std::collections::BTreeMap;
use std::fs;
use std::io::Read;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::thread;
use std::time::{Duration, Instant};

use std::sync::atomic::{AtomicU32, AtomicU8, AtomicUsize, Ordering};

// Bound (max Vec/slice length) and unwind (loop unroll depth) are user-tunable via
// --bound / --unwind, set once in main() before any verification. RANGE stays const:
// it defines the strict-vs-realistic split that the UNGUARDED classification rests on.
static BOUND_A: AtomicUsize = AtomicUsize::new(3);
static UNWIND_A: AtomicU32 = AtomicU32::new(5);
fn bound() -> usize {
    BOUND_A.load(Ordering::Relaxed)
}
fn unwind() -> u32 {
    UNWIND_A.load(Ordering::Relaxed)
}

// CI rigor dial (--fail-on): 0 = BUG only (default), 1 = + UNGUARDED, 2 = + INCONCLUSIVE.
static FAIL_ON: AtomicU8 = AtomicU8::new(0);
/// Does this verdict fail the gate at the current --fail-on level?
fn fails(v: &Verdict) -> bool {
    let level = FAIL_ON.load(Ordering::Relaxed);
    match v {
        Verdict::Bug(..) => true,
        Verdict::Unguarded(_) => level >= 1,
        Verdict::Inconclusive => level >= 2,
        _ => false, // VERIFIED / UNSUPPORTED never fail
    }
}
const RANGE: i64 = 1000;
/// Per-mode wall-clock cap. Kani can run for minutes on adapter-heavy functions;
/// past this we report ⏱️ INCONCLUSIVE rather than hang a CI job forever.
const TIMEOUT_SECS: u64 = 120;
const SCALARS: &[&str] = &[
    "i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize", "bool",
];
const G: &str = "\x1b[32m";
const R: &str = "\x1b[31m";
const Y: &str = "\x1b[33m";
const B: &str = "\x1b[1m";
const DIM: &str = "\x1b[2m";
const X: &str = "\x1b[0m";

fn helper() -> String {
    format!(
        r#"// auto-generated by cargo-aiv
fn any_bounded_vec<T: kani::Arbitrary>(bound: usize) -> Vec<T> {{
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<T> = Vec::with_capacity(len);
    for _ in 0..len {{ v.push(kani::any()); }}
    v
}}
fn any_bounded_vec_ranged(bound: usize) -> Vec<i32> {{
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<i32> = Vec::with_capacity(len);
    for _ in 0..len {{ let x: i32 = kani::any(); kani::assume(x >= -{RANGE} && x <= {RANGE}); v.push(x); }}
    v
}}"#
    )
}

fn path_head(ty: &syn::Type) -> Option<(String, Vec<syn::Type>)> {
    if let syn::Type::Path(tp) = ty {
        if let Some(seg) = tp.path.segments.last() {
            let mut args = Vec::new();
            if let syn::PathArguments::AngleBracketed(ab) = &seg.arguments {
                for a in &ab.args {
                    if let syn::GenericArgument::Type(t) = a {
                        args.push(t.clone());
                    }
                }
            }
            return Some((seg.ident.to_string(), args));
        }
    }
    None
}

fn scalar_int(ty: &syn::Type) -> Option<String> {
    let (base, args) = path_head(ty)?;
    (args.is_empty() && SCALARS.contains(&base.as_str())).then_some(base)
}

/// A bounded symbolic `Vec<et>` binding line. `mutable` makes it `let mut`.
fn vec_binding(name: &str, et: &str, realistic: bool, mutable: bool) -> String {
    let m = if mutable { "mut " } else { "" };
    let bound = bound();
    if realistic && et == "i32" {
        format!("    let {m}{name}: Vec<i32> = any_bounded_vec_ranged({bound});")
    } else {
        format!("    let {m}{name}: Vec<{et}> = any_bounded_vec::<{et}>({bound});")
    }
}

/// Map a parameter to (binding line(s), argument expression at the call site).
/// The arg expr differs from the name for by-reference params (`&v`, `&mut v`).
fn map_input(name: &str, ty: &syn::Type, realistic: bool) -> Option<(String, String)> {
    if let Some(s) = scalar_int(ty) {
        let mut line = format!("    let {name}: {s} = kani::any();");
        if realistic && s.starts_with('i') {
            line += &format!("\n    kani::assume({name} >= -{RANGE} && {name} <= {RANGE});");
        } else if realistic && s.starts_with('u') {
            line += &format!("\n    kani::assume({name} <= {RANGE});");
        }
        return Some((line, name.to_string()));
    }
    // &[int] / &mut [int] — bind a symbolic Vec and pass it by reference (a `&Vec`
    // coerces to `&[T]`). Covers slice params, extremely common in AI Rust.
    if let syn::Type::Reference(r) = ty {
        if let syn::Type::Slice(sl) = &*r.elem {
            let et = scalar_int(&sl.elem)?;
            let mutable = r.mutability.is_some();
            let arg = if mutable {
                format!("&mut {name}")
            } else {
                format!("&{name}")
            };
            return Some((vec_binding(name, &et, realistic, mutable), arg));
        }
        // &Vec<int> / &mut Vec<int>
        if let Some(("Vec", inner)) = path_head(&r.elem).as_ref().map(|(b, a)| (b.as_str(), a)) {
            let et = scalar_int(inner.first()?)?;
            let mutable = r.mutability.is_some();
            let arg = if mutable {
                format!("&mut {name}")
            } else {
                format!("&{name}")
            };
            return Some((vec_binding(name, &et, realistic, mutable), arg));
        }
    }
    // (i32, u8, ...) — a tuple of scalar ints. Bind one kani::any() per element,
    // with per-element realistic assumes on the tuple fields.
    if let syn::Type::Tuple(tup) = ty {
        if tup.elems.is_empty() {
            return None; // unit () — nothing to synthesize
        }
        let mut types = Vec::new();
        for el in &tup.elems {
            types.push(scalar_int(el)?); // any non-scalar element ⇒ unsupported
        }
        let anys: Vec<&str> = types.iter().map(|_| "kani::any()").collect();
        let tystr = format!("({})", types.join(", "));
        let mut line = format!("    let {name}: {tystr} = ({});", anys.join(", "));
        if realistic {
            for (i, s) in types.iter().enumerate() {
                if s.starts_with('i') {
                    line += &format!(
                        "\n    kani::assume({name}.{i} >= -{RANGE} && {name}.{i} <= {RANGE});"
                    );
                } else if s.starts_with('u') {
                    line += &format!("\n    kani::assume({name}.{i} <= {RANGE});");
                }
            }
        }
        return Some((line, name.to_string()));
    }
    let (base, args) = path_head(ty)?;
    match (base.as_str(), args.as_slice()) {
        ("Vec", [inner]) => {
            let et = scalar_int(inner)?;
            Some((vec_binding(name, &et, realistic, false), name.to_string()))
        }
        ("Option", [inner]) => {
            let et = scalar_int(inner)?;
            let tystr = quote!(#ty).to_string().replace(' ', "");
            let mut line = format!("    let {name}: {tystr} = kani::any();");
            // Clamp the Some(_) payload in realistic mode too — otherwise an Option
            // overflow at i32::MAX is misreported as BUG instead of UNGUARDED.
            if realistic && et.starts_with('i') {
                line += &format!(
                    "\n    if let Some(v) = {name} {{ kani::assume(v >= -{RANGE} && v <= {RANGE}); }}"
                );
            } else if realistic && et.starts_with('u') {
                line += &format!("\n    if let Some(v) = {name} {{ kani::assume(v <= {RANGE}); }}");
            }
            Some((line, name.to_string()))
        }
        _ => None,
    }
}

/// Generate just the Kani proof harness for ONE function. Err(msg) if any param
/// is unsupported. `postcond`, if set, becomes the proof obligation instead of the
/// default panic-freedom check.
fn harness_for(
    func: &syn::ItemFn,
    realistic: bool,
    postcond: Option<&str>,
) -> Result<String, String> {
    let name = func.sig.ident.to_string();
    let mut inputs = Vec::new();
    let mut args = Vec::new();
    for arg in &func.sig.inputs {
        match arg {
            syn::FnArg::Typed(pt) => {
                let pname = match &*pt.pat {
                    syn::Pat::Ident(pi) => pi.ident.to_string(),
                    _ => return Err(format!("unsupported parameter pattern in `{name}`")),
                };
                let (line, arg_expr) = map_input(&pname, &pt.ty, realistic).ok_or_else(|| {
                    format!("`{name}` param `{pname}: {}` unsupported (v0: scalar ints, Vec<int>, Option<int>, &[int], tuples)", quote!(#pt))
                })?;
                inputs.push(line);
                args.push(arg_expr);
            }
            syn::FnArg::Receiver(_) => return Err(format!("`{name}` is a method (self)")),
        }
    }
    let call = args.join(", ");
    let tail = match postcond {
        Some(expr) => format!(
            "    let result = {name}({call});\n    kani::assert({expr}, \"aiv postcondition\");\n    let _ = &result;"
        ),
        None => format!("    let _ = {name}({call});"),
    };
    let uw = unwind();
    Ok(format!(
        "#[kani::proof]\n#[kani::unwind({uw})]\nfn verify_{name}() {{\n{}\n{}\n}}",
        inputs.join("\n"),
        tail,
    ))
}

/// Recursively collect `.rs` files under `dir` in a deterministic (sorted) order.
fn collect_rs(dir: &std::path::Path, out: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut paths: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
    paths.sort();
    for p in paths {
        if p.is_dir() {
            collect_rs(&p, out);
        } else if p.extension().is_some_and(|e| e == "rs") {
            out.push(p.to_string_lossy().into_owned());
        }
    }
}

fn first_fn(file: &syn::File) -> Option<&syn::ItemFn> {
    file.items.iter().find_map(|it| {
        if let syn::Item::Fn(f) = it {
            Some(f)
        } else {
            None
        }
    })
}

/// Build a lib.rs for a SINGLE function (the first one) — used by --emit / --prove.
fn build(src: &str, realistic: bool, postcond: Option<&str>) -> Result<(String, String), String> {
    let file = syn::parse_file(src).map_err(|e| format!("parse error: {e}"))?;
    let func = first_fn(&file).ok_or("no top-level function found")?;
    let name = func.sig.ident.to_string();
    let harness = harness_for(func, realistic, postcond)?;
    let lib = format!("{}\n\n{}\n\n{harness}\n", helper(), src.trim());
    Ok((name, lib))
}

/// Per-function build status: `None` = supported (harness emitted), `Some(reason)`
/// = skipped, in source order.
type FnStatuses = Vec<(String, Option<String>)>;

/// Build a lib.rs with a harness for EVERY top-level function (real source files
/// have many). Returns per-fn status plus the combined lib.
fn build_all(src: &str, realistic: bool) -> Result<(FnStatuses, String), String> {
    let file = syn::parse_file(src).map_err(|e| format!("parse error: {e}"))?;
    let funcs: Vec<&syn::ItemFn> = file
        .items
        .iter()
        .filter_map(|it| {
            if let syn::Item::Fn(f) = it {
                Some(f)
            } else {
                None
            }
        })
        .collect();
    if funcs.is_empty() {
        return Err("no top-level function found".into());
    }
    let mut statuses = Vec::new();
    let mut harnesses = Vec::new();
    for f in &funcs {
        let name = f.sig.ident.to_string();
        match harness_for(f, realistic, None) {
            Ok(h) => {
                statuses.push((name, None));
                harnesses.push(h);
            }
            Err(e) => statuses.push((name, Some(e))),
        }
    }
    let lib = format!(
        "{}\n\n{}\n\n{}\n",
        helper(),
        src.trim(),
        harnesses.join("\n\n")
    );
    Ok((statuses, lib))
}

/// Run `cargo kani` in `dir`, draining stdout+stderr on threads (so a full pipe
/// buffer can't deadlock the child) and killing it past `TIMEOUT_SECS`.
/// Returns None if the run timed out or couldn't start.
fn kani_output(dir: &PathBuf) -> Option<String> {
    let mut child = Command::new("cargo")
        .arg("kani")
        .current_dir(dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .ok()?;
    let mut so = child.stdout.take()?;
    let mut se = child.stderr.take()?;
    let ho = thread::spawn(move || {
        let mut s = String::new();
        so.read_to_string(&mut s).ok();
        s
    });
    let he = thread::spawn(move || {
        let mut s = String::new();
        se.read_to_string(&mut s).ok();
        s
    });
    let start = Instant::now();
    loop {
        match child.try_wait() {
            Ok(Some(_)) => break,
            Ok(None) => {
                if start.elapsed() > Duration::from_secs(TIMEOUT_SECS) {
                    let _ = child.kill();
                    let _ = child.wait();
                    return None; // timed out — pipes hit EOF, reader threads unblock
                }
                thread::sleep(Duration::from_millis(200));
            }
            Err(_) => return None,
        }
    }
    Some(ho.join().unwrap_or_default() + &he.join().unwrap_or_default())
}

fn run_kani(dir: &PathBuf, name: &str, lib: &str) -> Option<BTreeMap<String, (bool, Vec<String>)>> {
    fs::create_dir_all(dir.join("src")).ok();
    fs::write(
        dir.join("Cargo.toml"),
        format!("[package]\nname = \"aiv_{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\n"),
    )
    .ok();
    fs::write(dir.join("src/lib.rs"), lib).ok();
    let text = kani_output(dir)?;
    let mut res = BTreeMap::new();
    let mut cur = String::new();
    for ln in text.lines() {
        if let Some(i) = ln.find("Checking harness verify_") {
            cur = ln[i + "Checking harness verify_".len()..]
                .split(['.', ' '])
                .next()
                .unwrap_or("")
                .to_string();
            res.insert(cur.clone(), (false, Vec::new()));
        } else if !cur.is_empty() && ln.contains("Failed Checks:") {
            if let Some(e) = res.get_mut(&cur) {
                e.1.push(
                    ln.split("Failed Checks:")
                        .nth(1)
                        .unwrap_or("")
                        .trim()
                        .to_string(),
                );
            }
        } else if !cur.is_empty() && ln.contains("VERIFICATION:-") {
            if let Some(e) = res.get_mut(&cur) {
                e.0 = ln.contains("FAILED");
            }
        }
    }
    Some(res)
}

/// Re-run a failing harness with concrete playback to extract the triggering input.
/// Returns (assertion message, symbolic input values in order).
fn counterexample(dir: &PathBuf, name: &str) -> Option<(String, Vec<String>)> {
    let out = Command::new("cargo")
        .args([
            "kani",
            "--harness",
            &format!("verify_{name}"),
            "-Z",
            "concrete-playback",
            "--concrete-playback=print",
        ])
        .current_dir(dir)
        .output()
        .ok()?;
    let text =
        String::from_utf8_lossy(&out.stdout).to_string() + &String::from_utf8_lossy(&out.stderr);
    parse_playback(&text)
}

/// Parse Kani `--concrete-playback=print` output into (assertion message, input
/// values in order). Pure so it can be unit-tested against captured Kani output.
///
/// Kani prints one `concrete_vals` block per failing check; each is a complete,
/// independent witness. We keep only the FIRST — merging tokens across blocks
/// produces a meaningless list (e.g. mixing a postcondition witness with a
/// separate panic witness).
fn parse_playback(text: &str) -> Option<(String, Vec<String>)> {
    let (mut assertion, mut vals, mut in_block, mut done) =
        (String::new(), Vec::new(), false, false);
    for ln in text.lines() {
        if assertion.is_empty() {
            if let Some(i) = ln.find("Check for `assertion`: \"") {
                assertion = ln[i + "Check for `assertion`: \"".len()..]
                    .trim_end_matches('"')
                    .to_string();
            }
        }
        if !done && ln.contains("let concrete_vals") {
            in_block = true;
            continue;
        }
        if in_block {
            let t = ln.trim();
            if t.starts_with("//") {
                vals.push(t.trim_start_matches("//").trim().to_string());
            }
            if t.contains("];") {
                in_block = false;
                done = true; // first block captured — ignore any further blocks
            }
        }
    }
    (!assertion.is_empty() || !vals.is_empty()).then_some((assertion, vals))
}

// Unit tests are kept next to the pure functions they cover; the CLI plumbing
// (main/batch/selftest) follows below, hence the allow.
#[cfg(test)]
#[allow(clippy::items_after_test_module)]
mod tests {
    use super::{build, interpret_val, map_input, parse_playback};

    #[test]
    fn tuple_param_binds_one_any_per_element() {
        let (name, lib) = build("fn f(p: (i32, u8)) -> i32 { 0 }", false, None).unwrap();
        assert_eq!(name, "f");
        assert!(lib.contains("let p: (i32, u8) = (kani::any(), kani::any());"));
        assert!(lib.contains("let _ = f(p);"));
    }

    #[test]
    fn slice_param_passes_by_reference() {
        let (_, lib) = build("fn g(xs: &[i32]) -> i32 { 0 }", false, None).unwrap();
        assert!(lib.contains("let xs: Vec<i32> = any_bounded_vec::<i32>(3);"));
        assert!(lib.contains("let _ = g(&xs);"));
    }

    #[test]
    fn postcondition_binds_result_and_asserts() {
        let (_, lib) = build("fn h(a: i32) -> i32 { a }", true, Some("result >= a")).unwrap();
        assert!(lib.contains("let result = h(a);"));
        assert!(lib.contains(r#"kani::assert(result >= a, "aiv postcondition");"#));
    }

    #[test]
    fn option_payload_clamped_in_realistic_not_strict() {
        // strict: no clamp on the Some payload
        let (_, strict) = build("fn f(o: Option<i32>) -> i32 { 0 }", false, None).unwrap();
        assert!(strict.contains("let o: Option<i32> = kani::any();"));
        assert!(!strict.contains("if let Some(v) = o"));
        // realistic: clamp Some(_) so an extreme-only overflow reads as UNGUARDED, not BUG
        let (_, real) = build("fn f(o: Option<i32>) -> i32 { 0 }", true, None).unwrap();
        assert!(real.contains("if let Some(v) = o { kani::assume(v >= -1000 && v <= 1000); }"));
    }

    #[test]
    fn collect_rs_finds_rs_recursively_sorted() {
        use super::collect_rs;
        use std::fs;
        let root = std::env::temp_dir().join("aiv-collect-test");
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("sub")).unwrap();
        fs::write(root.join("b.rs"), "").unwrap();
        fs::write(root.join("a.rs"), "").unwrap();
        fs::write(root.join("note.txt"), "").unwrap(); // ignored
        fs::write(root.join("sub").join("c.rs"), "").unwrap();
        let mut out = Vec::new();
        collect_rs(&root, &mut out);
        let names: Vec<String> = out
            .iter()
            .map(|p| {
                std::path::Path::new(p)
                    .file_name()
                    .unwrap()
                    .to_string_lossy()
                    .into_owned()
            })
            .collect();
        assert_eq!(names, vec!["a.rs", "b.rs", "c.rs"]); // sorted, recursive, .txt skipped
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn build_all_emits_a_harness_per_function() {
        use super::build_all;
        let src = "fn a(x: i32) -> i32 { x }\nfn b(s: &str) -> i32 { 0 }\nfn c(v: Vec<i32>) -> i32 { v[0] }";
        let (statuses, lib) = build_all(src, false).unwrap();
        let names: Vec<&str> = statuses.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, vec!["a", "b", "c"]);
        // a and c are supported → harnesses present; b (&str) is skipped with a reason
        assert!(statuses[0].1.is_none());
        assert!(statuses[1].1.is_some());
        assert!(statuses[2].1.is_none());
        assert!(lib.contains("fn verify_a()"));
        assert!(lib.contains("fn verify_c()"));
        assert!(!lib.contains("fn verify_b()"));
    }

    #[test]
    fn unsupported_param_is_rejected() {
        assert!(map_input("s", &syn::parse_str("&str").unwrap(), false).is_none());
        assert!(build("fn f(s: &str) {}", false, None).is_err());
    }

    #[test]
    fn json_escapes_special_chars() {
        use super::json_escape;
        assert_eq!(json_escape(r#"a"b\c"#), r#"a\"b\\c"#);
        assert_eq!(json_escape("line\nbreak"), "line\\nbreak");
    }

    #[test]
    fn verdict_json_shapes() {
        use super::{verdict_json, Verdict};
        let bug = Verdict::Bug(vec!["divide by zero".into()], vec!["0".into()]);
        assert_eq!(
            verdict_json("swap_div", &bug),
            r#"{"name":"swap_div","verdict":"BUG","checks":["divide by zero"],"witness":["0"]}"#
        );
        assert_eq!(
            verdict_json("ok", &Verdict::Verified),
            r#"{"name":"ok","verdict":"VERIFIED","checks":[],"witness":[]}"#
        );
    }

    // Two failing checks → two concrete_vals blocks. We must keep only the first
    // witness, not merge tokens across blocks (the find_max --prove regression).
    #[test]
    fn playback_keeps_only_first_witness_block() {
        let kani = r#"
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 1ul
        vec![1, 0, 0, 0, 0, 0, 0, 0],
        // -1
        vec![255, 255, 255, 255],
    ];
    kani::concrete_playback_run(concrete_vals, verify_find_max);
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 0ul
        vec![0, 0, 0, 0, 0, 0, 0, 0],
    ];
"#;
        let (_, vals) = parse_playback(kani).unwrap();
        assert_eq!(vals, vec!["1ul", "-1"]); // NOT ["1ul","-1","0ul"]
    }

    // One failing check with two params → one block holding all param values.
    // The first-block rule must NOT truncate this (the dot_index case).
    #[test]
    fn playback_keeps_all_params_in_one_block() {
        let kani = r#"
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 1ul
        vec![1, 0, 0, 0, 0, 0, 0, 0],
        // -1
        vec![255, 255, 255, 255],
        // 0ul
        vec![0, 0, 0, 0, 0, 0, 0, 0],
    ];
"#;
        let (_, vals) = parse_playback(kani).unwrap();
        assert_eq!(vals, vec!["1ul", "-1", "0ul"]);
    }

    #[test]
    fn playback_captures_assertion_message() {
        let kani = "Check for `assertion`: \"attempt to add with overflow\"\n    let concrete_vals: Vec<Vec<u8>> = vec![\n        // 5i32\n    ];";
        let (msg, vals) = parse_playback(kani).unwrap();
        assert_eq!(msg, "attempt to add with overflow");
        assert_eq!(vals, vec!["5i32"]);
    }

    #[test]
    fn playback_none_when_no_block() {
        assert!(parse_playback("VERIFICATION:- SUCCESSFUL\n").is_none());
    }

    #[test]
    fn fail_on_levels_gate_correctly() {
        use super::{fails, Verdict, FAIL_ON};
        use std::sync::atomic::Ordering;
        let bug = Verdict::Bug(vec![], vec![]);
        let ung = Verdict::Unguarded(vec![]);
        let inc = Verdict::Inconclusive;
        let ver = Verdict::Verified;
        FAIL_ON.store(0, Ordering::Relaxed); // bug only (default)
        assert!(fails(&bug) && !fails(&ung) && !fails(&inc) && !fails(&ver));
        FAIL_ON.store(1, Ordering::Relaxed); // + unguarded
        assert!(fails(&bug) && fails(&ung) && !fails(&inc) && !fails(&ver));
        FAIL_ON.store(2, Ordering::Relaxed); // + inconclusive
        assert!(fails(&bug) && fails(&ung) && fails(&inc) && !fails(&ver));
        FAIL_ON.store(0, Ordering::Relaxed); // reset for other tests
    }

    #[test]
    fn unwinding_assertions_are_not_real_failures() {
        use super::real_failures;
        // a loop that overran the unwind bound is NOT a bug — filtered out
        let only_unwind = vec!["unwinding assertion loop 0".to_string()];
        assert!(real_failures(&only_unwind).is_empty());
        // a genuine panic is kept
        let mixed = vec![
            "unwinding assertion loop 0".to_string(),
            "attempt to multiply with overflow".to_string(),
        ];
        assert_eq!(
            real_failures(&mixed),
            vec!["attempt to multiply with overflow"]
        );
    }

    #[test]
    fn usize_reads_as_vector_length() {
        assert_eq!(interpret_val("0ul"), "0 (usize → empty vector)");
        assert_eq!(interpret_val("1ul"), "1 (usize → 1-element vector)");
        assert_eq!(interpret_val("3ul"), "3 (usize → vector of length 3)");
    }
    #[test]
    fn names_overflow_sentinels() {
        assert_eq!(interpret_val("-2147483648i32"), "-2147483648 (i32::MIN)");
        assert_eq!(interpret_val("2147483647i32"), "2147483647 (i32::MAX)");
        assert_eq!(interpret_val("127i8"), "127 (i8::MAX)");
        assert_eq!(interpret_val("255u8"), "255 (u8::MAX)");
    }
    #[test]
    fn ordinary_values_pass_through_without_suffix() {
        assert_eq!(interpret_val("5i32"), "5");
        assert_eq!(interpret_val("-3i64"), "-3");
        assert_eq!(interpret_val("42"), "42");
        assert_eq!(interpret_val("true"), "true");
        // a non-extreme value that shares a width but isn't the sentinel
        assert_eq!(interpret_val("100i8"), "100");
    }
}

/// Turn a raw Kani concrete value token (`"0ul"`, `"-2147483648i32"`, `"true"`)
/// into something a human reads at a glance. Conservative: only annotates values
/// it can identify unambiguously (usize length, min/max sentinels); otherwise
/// strips the type suffix and passes the number through.
fn interpret_val(tok: &str) -> String {
    let t = tok.trim();
    if t == "true" || t == "false" {
        return t.to_string();
    }
    // split "-123" core from "i32"/"ul"/... suffix
    let split = t.find(|c: char| c.is_ascii_alphabetic() && c != '-');
    let (core, suffix) = match split {
        Some(i) => (&t[..i], &t[i..]),
        None => (t, ""),
    };
    // usize only ever appears as a symbolic Vec/slice length in our harnesses
    if suffix == "ul" || suffix == "usize" {
        return match core {
            "0" => "0 (usize → empty vector)".to_string(),
            "1" => "1 (usize → 1-element vector)".to_string(),
            n => format!("{n} (usize → vector of length {n})"),
        };
    }
    // name overflow sentinels (min/max for the signed/unsigned width)
    let sentinel = match (suffix, core) {
        ("i8", "-128") => Some("i8::MIN"),
        ("i8", "127") => Some("i8::MAX"),
        ("i16", "-32768") => Some("i16::MIN"),
        ("i16", "32767") => Some("i16::MAX"),
        ("i32", "-2147483648") => Some("i32::MIN"),
        ("i32", "2147483647") => Some("i32::MAX"),
        ("i64" | "isize", "-9223372036854775808") => Some("i64::MIN"),
        ("i64" | "isize", "9223372036854775807") => Some("i64::MAX"),
        ("u8", "255") => Some("u8::MAX"),
        ("u16", "65535") => Some("u16::MAX"),
        ("u32", "4294967295") => Some("u32::MAX"),
        _ => None,
    };
    match sentinel {
        Some(name) => format!("{core} ({name})"),
        None => core.to_string(),
    }
}

enum Verdict {
    Verified,
    Bug(Vec<String>, Vec<String>), // failed checks, counterexample value tokens
    Unguarded(Vec<String>),        // overflow only at extremes
    Inconclusive,
    Unsupported(String),
}

fn json_escape(s: &str) -> String {
    let mut o = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            '\n' => o.push_str("\\n"),
            '\r' => o.push_str("\\r"),
            '\t' => o.push_str("\\t"),
            c if (c as u32) < 0x20 => o.push_str(&format!("\\u{:04x}", c as u32)),
            c => o.push(c),
        }
    }
    o
}

/// One result as a JSON object. `witness` values are the human-readable form.
fn verdict_json(label: &str, v: &Verdict) -> String {
    let (kind, checks, witness): (&str, Vec<String>, Vec<String>) = match v {
        Verdict::Verified => ("VERIFIED", vec![], vec![]),
        Verdict::Bug(c, w) => (
            "BUG",
            c.clone(),
            w.iter().map(|x| interpret_val(x)).collect(),
        ),
        Verdict::Unguarded(c) => ("UNGUARDED", c.clone(), vec![]),
        Verdict::Inconclusive => ("INCONCLUSIVE", vec![], vec![]),
        Verdict::Unsupported(e) => ("UNSUPPORTED", vec![e.clone()], vec![]),
    };
    let arr = |xs: &[String]| {
        xs.iter()
            .map(|x| format!("\"{}\"", json_escape(x)))
            .collect::<Vec<_>>()
            .join(",")
    };
    format!(
        "{{\"name\":\"{}\",\"verdict\":\"{}\",\"checks\":[{}],\"witness\":[{}]}}",
        json_escape(label),
        kind,
        arr(&checks),
        arr(&witness)
    )
}

/// Emit `{"results":[...],"summary":{...}}` for a set of labelled verdicts.
fn emit_json(results: &[(&str, &Verdict)]) {
    let count = |p: fn(&Verdict) -> bool| results.iter().filter(|(_, v)| p(v)).count();
    let bugs = count(|v| matches!(v, Verdict::Bug(..)));
    let ung = count(|v| matches!(v, Verdict::Unguarded(_)));
    let ver = count(|v| matches!(v, Verdict::Verified));
    let other = results.len() - bugs - ung - ver;
    let items: Vec<String> = results.iter().map(|(l, v)| verdict_json(l, v)).collect();
    println!(
        "{{\"results\":[{}],\"summary\":{{\"bug\":{bugs},\"unguarded\":{ung},\"verified\":{ver},\"other\":{other}}}}}",
        items.join(",")
    );
}

/// Keep only genuine panic/overflow checks. An "unwinding assertion" failure is NOT
/// a panic — it means a loop wasn't fully unrolled within the unwind bound, so the
/// check is incomplete. Unwinding-only failures must classify as INCONCLUSIVE, never
/// BUG/UNGUARDED (that would be a false verdict — the very thing this tool prevents).
fn real_failures(checks: &[String]) -> Vec<String> {
    checks
        .iter()
        .filter(|c| !c.contains("unwinding assertion"))
        .cloned()
        .collect()
}

type KaniMap = BTreeMap<String, (bool, Vec<String>)>;

/// Dual-mode classify for one function from its strict+realistic Kani results.
fn classify(name: &str, realistic_dir: &PathBuf, strict: &KaniMap, real: &KaniMap) -> Verdict {
    let s = strict.get(name).cloned().unwrap_or((false, vec![]));
    let r = real.get(name).cloned().unwrap_or((false, vec![]));
    let s_real = real_failures(&s.1);
    let r_real = real_failures(&r.1);
    if !s.0 {
        Verdict::Verified
    } else if s_real.is_empty() {
        // strict failed only on unwinding assertions — couldn't fully check the loop
        Verdict::Inconclusive
    } else if !r_real.is_empty() {
        let vals = counterexample(realistic_dir, name)
            .map(|(_, v)| v)
            .unwrap_or_default();
        Verdict::Bug(r_real, vals)
    } else {
        Verdict::Unguarded(s_real)
    }
}

/// Verify EVERY top-level function in a source file (real files have many). Returns
/// (name, verdict) per function in source order. `slot` + PID namespace the temp dir
/// so concurrent workers never collide.
fn verify_file(src: &str, slot: usize) -> Vec<(String, Verdict)> {
    let (statuses, strict_lib) = match build_all(src, false) {
        Ok(v) => v,
        Err(e) => return vec![(String::new(), Verdict::Unsupported(e))],
    };
    let real_lib = build_all(src, true).unwrap().1;
    let base = std::env::temp_dir().join(format!("cargo-aiv-{}-multi-{slot}", std::process::id()));
    let realistic_dir = base.join("realistic");
    let (strict, real) = match (
        run_kani(&base.join("strict"), "multi", &strict_lib),
        run_kani(&realistic_dir, "multi", &real_lib),
    ) {
        (Some(s), Some(r)) => (s, r),
        // whole-file run timed out: supported fns are inconclusive, unsupported stay so
        _ => {
            return statuses
                .into_iter()
                .map(|(n, st)| match st {
                    Some(e) => (n, Verdict::Unsupported(e)),
                    None => (n, Verdict::Inconclusive),
                })
                .collect()
        }
    };
    statuses
        .into_iter()
        .map(|(name, st)| match st {
            Some(e) => (name, Verdict::Unsupported(e)),
            None => {
                let v = classify(&name, &realistic_dir, &strict, &real);
                (name, v)
            }
        })
        .collect()
}

/// Exit code convention shared by single-file and batch: BUG → 1, else 0
/// (INCONCLUSIVE stays 2 in single-file for back-compat).
fn verdict_code(v: &Verdict) -> i32 {
    match v {
        Verdict::Bug(..) => 1,
        Verdict::Inconclusive => 2,
        Verdict::Unsupported(_) => 1,
        _ => 0,
    }
}

/// Detailed single-file report. Returns the process exit code.
fn print_detailed(name: &str, v: &Verdict) -> i32 {
    println!();
    match v {
        Verdict::Verified => {
            println!(
                "{G}{B}✅ VERIFIED{X}  `{name}` — panic-free for Vec≤{}, |val|≤{RANGE}.",
                bound()
            );
        }
        Verdict::Bug(checks, vals) => {
            println!("{R}{B}🔴 BUG{X}  `{name}` — panic reachable on ordinary input:");
            for c in checks {
                println!("     {R}• {c}{X}");
            }
            if !vals.is_empty() {
                let pretty: Vec<String> = vals.iter().map(|v| interpret_val(v)).collect();
                println!(
                    "     {DIM}reachable with input(s), in order: {}{X}",
                    pretty.join(", ")
                );
            }
        }
        Verdict::Unguarded(checks) => {
            println!("{Y}{B}🟡 UNGUARDED{X}  `{name}` — safe on normal input, but overflows at i32::MAX/MIN:");
            for c in checks {
                println!("     {Y}• {c}{X}");
            }
            println!("     {DIM}add a bounds guard or use checked_/saturating_ arithmetic.{X}");
        }
        Verdict::Inconclusive => {
            println!(
                "{Y}{B}⏱️  INCONCLUSIVE{X}  `{name}` — didn't finish within {TIMEOUT_SECS}s/mode."
            );
            println!("     {DIM}too complex to prove at the current bounds (Vec≤{}, unwind {}). Not a pass — not a bug.{X}", bound(), unwind());
        }
        Verdict::Unsupported(e) => {
            println!("{Y}⏭  cargo-aiv: {e}{X}");
        }
    }
    verdict_code(v)
}

/// Batch mode: verify every file in parallel (bounded workers), print a compact
/// table in input order, exit 1 if any BUG. Parallelism is what makes verifying a
/// whole crate tractable — sequential Kani runs over N functions don't scale.
fn batch(files: &[String], json: bool) -> i32 {
    let tag = |v: &Verdict| match v {
        Verdict::Verified => format!("{G}✅ VERIFIED{X}"),
        Verdict::Bug(..) => format!("{R}🔴 BUG{X}"),
        Verdict::Unguarded(_) => format!("{Y}🟡 UNGUARDED{X}"),
        Verdict::Inconclusive => format!("{Y}⏱️  INCONCLUSIVE{X}"),
        Verdict::Unsupported(_) => format!("{DIM}⏭  unsupported{X}"),
    };
    // Kani/CBMC is CPU- and memory-heavy and already multi-threaded, so each run
    // wants most of the machine. Over-parallelizing starves individual runs past
    // their timeout → FALSE ⏱️ INCONCLUSIVE. Keep concurrency low: ~cores/4, ≤3.
    let workers = std::thread::available_parallelism()
        .map(|n| (n.get() / 4).max(1))
        .unwrap_or(2)
        .clamp(1, 3)
        .min(files.len().max(1));
    if !json {
        println!(
            "{DIM}cargo-aiv batch — {} file(s), {workers} workers, ≤{TIMEOUT_SECS}s/mode each{X}\n",
            files.len()
        );
    }
    let next = std::sync::atomic::AtomicUsize::new(0);
    let results: std::sync::Mutex<Vec<(usize, String, Verdict)>> =
        std::sync::Mutex::new(Vec::new());
    thread::scope(|scope| {
        for _ in 0..workers {
            scope.spawn(|| loop {
                let i = next.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                if i >= files.len() {
                    break;
                }
                let f = &files[i];
                match fs::read_to_string(f) {
                    Ok(src) => {
                        // one file can hold many functions — record a row per function
                        for (name, v) in verify_file(&src, i) {
                            let label = if name.is_empty() { f.clone() } else { name };
                            results.lock().unwrap().push((i, label, v));
                        }
                    }
                    Err(e) => results.lock().unwrap().push((
                        i,
                        f.clone(),
                        Verdict::Unsupported(e.to_string()),
                    )),
                }
            });
        }
    });
    let mut out = results.into_inner().unwrap();
    out.sort_by_key(|(i, _, _)| *i);
    let (mut bugs, mut ung, mut ver, mut other) = (0, 0, 0, 0);
    for (_, _, v) in &out {
        match v {
            Verdict::Bug(..) => bugs += 1,
            Verdict::Unguarded(_) => ung += 1,
            Verdict::Verified => ver += 1,
            _ => other += 1,
        }
    }
    let exit = i32::from(out.iter().any(|(_, _, v)| fails(v)));
    if json {
        let refs: Vec<(&str, &Verdict)> = out.iter().map(|(_, l, v)| (l.as_str(), v)).collect();
        emit_json(&refs);
        return exit;
    }
    for (_, label, v) in &out {
        let detail = match v {
            Verdict::Bug(_, vals) if !vals.is_empty() => {
                let p: Vec<String> = vals.iter().map(|x| interpret_val(x)).collect();
                format!("  {DIM}← {}{X}", p.join(", "))
            }
            _ => String::new(),
        };
        println!("  {:<22} {}{}", label, tag(v), detail);
    }
    println!(
        "\n{DIM}────{X}\n{R}{bugs} BUG{X} · {Y}{ung} UNGUARDED{X} · {G}{ver} VERIFIED{X} · {other} other"
    );
    exit
}

fn verdict_kind(v: &Verdict) -> &'static str {
    match v {
        Verdict::Verified => "VERIFIED",
        Verdict::Bug(..) => "BUG",
        Verdict::Unguarded(_) => "UNGUARDED",
        Verdict::Inconclusive => "INCONCLUSIVE",
        Verdict::Unsupported(_) => "UNSUPPORTED",
    }
}

/// Sanity-check the Kani wiring in the user's environment: a verifier that silently
/// passes everything (Kani missing / output format drifted) is worse than useless.
/// Run a function that MUST be BUG and one that MUST be VERIFIED; fail loudly if the
/// tool can't tell them apart.
fn selftest() -> i32 {
    println!("{DIM}cargo-aiv self-test — checking the Kani wiring in this environment…{X}");
    let one = |src: &str, slot| verify_file(src, slot).pop().map(|(_, v)| v).unwrap();
    let bug = one("fn aiv_bug(v: Vec<i32>) -> i32 { v[0] }", 900);
    let safe = one("fn aiv_safe(x: i32) -> i32 { x }", 901);
    let bug_ok = matches!(bug, Verdict::Bug(..));
    let safe_ok = matches!(safe, Verdict::Verified);
    let mark = |ok: bool| {
        if ok {
            format!("{G}OK{X}")
        } else {
            format!("{R}WRONG{X}")
        }
    };
    println!(
        "  known-bug  `v[0]` on empty vec → {:<12} expect BUG       {}",
        verdict_kind(&bug),
        mark(bug_ok)
    );
    println!(
        "  known-safe identity fn         → {:<12} expect VERIFIED  {}",
        verdict_kind(&safe),
        mark(safe_ok)
    );
    if bug_ok && safe_ok {
        println!("{G}{B}PASS{X} — Kani is wired correctly; verdicts are trustworthy.");
        0
    } else {
        println!(
            "{R}{B}FAIL{X} — the tool is NOT distinguishing known cases; DO NOT trust its results."
        );
        println!("     {DIM}Is Kani installed and set up?  cargo install --locked kani-verifier && cargo kani setup{X}");
        1
    }
}

fn main() {
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    if args.first().map(|s| s.as_str()) == Some("aiv") {
        args.remove(0); // invoked as `cargo aiv ...`
    }
    if args.iter().any(|a| a == "--version" || a == "-V") {
        println!("cargo-aiv {}", env!("CARGO_PKG_VERSION"));
        return;
    }
    if args.iter().any(|a| a == "--selftest") {
        std::process::exit(selftest());
    }
    if args.is_empty() || args.iter().any(|a| a == "--help" || a == "-h") {
        print!(
            "\
cargo-aiv {ver} — prove AI-generated Rust is panic-free (don't just test it)

USAGE:
    cargo-aiv <file.rs>...             verify one file, or many (batch table)
    cargo-aiv --prove '<expr>' <file>  prove a postcondition over `result`/inputs
    cargo-aiv --emit <file.rs>         print the generated Kani harness, don't run
    cargo-aiv --json <file.rs>...      machine-readable results (single or batch)
    cargo-aiv --selftest               check Kani is wired correctly (trust guard)

OPTIONS:
    --bound N          max Vec/slice length to check (default 3)
    --unwind N         loop unroll depth (default 5)
    --fail-on <level>  which verdicts exit non-zero: bug (default) | unguarded | inconclusive

VERDICTS:
    🔴 BUG          panic reachable on ordinary input (exit 1) — with a witness
    🟡 UNGUARDED    overflows only at i32::MAX/MIN — add a guard (exit 0)
    ✅ VERIFIED     provably panic-free within bounds (exit 0)
    ⏱️  INCONCLUSIVE didn't finish within {t}s/mode (exit 2)
    ⏭  unsupported  a type outside v0 scope — skipped cleanly

Supported params: scalar ints, Vec<int>, Option<int>, &[int]/&mut [int], (int, int).
Requires Kani: cargo install --locked kani-verifier && cargo kani setup
Docs: https://github.com/ss1738/cargo-aiv
",
            ver = env!("CARGO_PKG_VERSION"),
            t = TIMEOUT_SECS
        );
        return;
    }
    let emit = args.iter().any(|a| a == "--emit");
    let json = args.iter().any(|a| a == "--json");
    // --prove '<expr>' consumes the following arg as the postcondition
    let mut prove: Option<String> = None;
    if let Some(i) = args.iter().position(|a| a == "--prove") {
        match args.get(i + 1).cloned() {
            Some(expr) => {
                prove = Some(expr);
                args.drain(i..=i + 1);
            }
            None => {
                eprintln!("usage: cargo-aiv --prove '<bool expr over result/inputs>' <file.rs>");
                std::process::exit(2);
            }
        }
    }
    // --bound N / --unwind N override the BMC depth. Drain the value too so it's
    // not mistaken for a file path.
    if let Some(i) = args.iter().position(|a| a == "--bound") {
        match args.get(i + 1).and_then(|s| s.parse::<usize>().ok()) {
            Some(v) if v >= 1 => {
                BOUND_A.store(v, Ordering::Relaxed);
                args.drain(i..=i + 1);
            }
            _ => {
                eprintln!("--bound needs a positive integer");
                std::process::exit(2);
            }
        }
    }
    if let Some(i) = args.iter().position(|a| a == "--unwind") {
        match args.get(i + 1).and_then(|s| s.parse::<u32>().ok()) {
            Some(v) if v >= 1 => {
                UNWIND_A.store(v, Ordering::Relaxed);
                args.drain(i..=i + 1);
            }
            _ => {
                eprintln!("--unwind needs a positive integer");
                std::process::exit(2);
            }
        }
    }
    if let Some(i) = args.iter().position(|a| a == "--fail-on") {
        let level = match args.get(i + 1).map(|s| s.as_str()) {
            Some("bug") => 0,
            Some("unguarded") => 1,
            Some("inconclusive") => 2,
            _ => {
                eprintln!("--fail-on needs one of: bug | unguarded | inconclusive");
                std::process::exit(2);
            }
        };
        FAIL_ON.store(level, Ordering::Relaxed);
        args.drain(i..=i + 1);
    }
    let raw: Vec<String> = args
        .iter()
        .filter(|a| !a.starts_with("--"))
        .cloned()
        .collect();
    if raw.is_empty() {
        eprintln!("usage: cargo-aiv [--emit] [--prove '<expr>'] <file.rs | dir>...");
        std::process::exit(2);
    }
    // A directory argument expands to every .rs file under it (recursive) — so
    // `cargo-aiv src/` verifies a whole crate without a shell glob.
    let mut files = Vec::new();
    for a in &raw {
        let p = std::path::Path::new(a);
        if p.is_dir() {
            collect_rs(p, &mut files);
        } else {
            files.push(a.clone());
        }
    }
    if files.is_empty() {
        eprintln!("cargo-aiv: no .rs files found in {}", raw.join(", "));
        std::process::exit(2);
    }

    // Batch mode: 2+ files → summary table, one exit code (only with plain verify).
    if files.len() > 1 && !emit && prove.is_none() {
        std::process::exit(batch(&files, json));
    }

    let file = files[0].clone();
    let src = fs::read_to_string(&file).unwrap_or_else(|e| {
        eprintln!("cannot read {file}: {e}");
        std::process::exit(2);
    });

    if emit {
        match build(&src, prove.is_some(), prove.as_deref()) {
            Ok((_, lib)) => println!("{lib}"),
            Err(e) => {
                eprintln!("cargo-aiv: {e}");
                std::process::exit(1);
            }
        }
        return;
    }

    // --prove: check a postcondition over the return value (realistic bounds).
    if let Some(expr) = prove {
        let (name, lib) = match build(&src, true, Some(&expr)) {
            Ok(v) => v,
            Err(e) => {
                println!("{Y}⏭  cargo-aiv: {e}{X}");
                std::process::exit(1);
            }
        };
        println!(
            "{DIM}proving `{name}`: {B}{expr}{X}{DIM}  (all inputs, |val|≤{RANGE}, Vec≤{})…{X}",
            bound()
        );
        let dir =
            std::env::temp_dir().join(format!("cargo-aiv-{}-{name}-prove", std::process::id()));
        let res = match run_kani(&dir, &name, &lib) {
            Some(r) => r,
            None => {
                println!(
                    "\n{Y}{B}⏱️  INCONCLUSIVE{X}  `{name}` — didn't finish within {TIMEOUT_SECS}s."
                );
                std::process::exit(2);
            }
        };
        let v = res.get(&name).cloned().unwrap_or((false, vec![]));
        println!();
        if !v.0 {
            println!("{G}{B}✅ PROVEN{X}  `{name}` — {B}{expr}{X} holds for all inputs in bounds.");
            std::process::exit(0);
        }
        println!(
            "{R}{B}🔴 VIOLATED{X}  `{name}` — {B}{expr}{X} can be false (or the fn panics first):"
        );
        for c in &v.1 {
            println!("     {R}• {c}{X}");
        }
        if let Some((_a, vals)) = counterexample(&dir, &name) {
            if !vals.is_empty() {
                let pretty: Vec<String> = vals.iter().map(|v| interpret_val(v)).collect();
                println!(
                    "     {DIM}counterexample input(s), in order: {}{X}",
                    pretty.join(", ")
                );
            }
        }
        std::process::exit(1);
    }

    // Single-file verify: every top-level function, dual-mode classify.
    if !json {
        println!("{DIM}verifying `{file}` (strict + realistic bounded model checking, ≤{TIMEOUT_SECS}s/mode)…{X}");
    }
    let results = verify_file(&src, 0);
    let label = |n: &str| {
        if n.is_empty() {
            file.clone()
        } else {
            n.to_string()
        }
    };
    // exit 1 if any verdict fails the gate; else a lone INCONCLUSIVE keeps its
    // distinct exit 2 (couldn't check ≠ verified).
    let single_inconclusive = results.len() == 1 && matches!(results[0].1, Verdict::Inconclusive);
    let exit = if results.iter().any(|(_, v)| fails(v)) {
        1
    } else if single_inconclusive {
        2
    } else {
        0
    };
    if json {
        let labels: Vec<(String, &Verdict)> = results.iter().map(|(n, v)| (label(n), v)).collect();
        let refs: Vec<(&str, &Verdict)> = labels.iter().map(|(l, v)| (l.as_str(), *v)).collect();
        emit_json(&refs);
        std::process::exit(exit);
    }
    for (name, verdict) in &results {
        print_detailed(&label(name), verdict);
    }
    std::process::exit(exit);
}
