//! cargo-aiv — prove AI-generated Rust is panic-free (don't just test it).
//!
//! Parses a single-fn `.rs` with `syn`, auto-generates a Kani proof harness,
//! runs bounded model checking in TWO modes (strict + realistic), and reports:
//!   🔴 BUG        panic reachable on ordinary input — fix it
//!   🟡 UNGUARDED  overflow only at i32::MAX/MIN — add a guard (not a false alarm)
//!   ✅ VERIFIED   panic-free for Vec≤3, |val|≤1000
//!
//!   cargo-aiv <file.rs>          # verify (default)
//!   cargo-aiv --emit <file.rs>   # just print the generated harness

use quote::quote;
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

const BOUND: usize = 3;
const UNWIND: u32 = 5;
const RANGE: i64 = 1000;
const SCALARS: &[&str] = &[
    "i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize", "bool",
];
const G: &str = "\x1b[32m";
const R: &str = "\x1b[31m";
const Y: &str = "\x1b[33m";
const B: &str = "\x1b[1m";
const DIM: &str = "\x1b[2m";
const X: &str = "\x1b[0m";

fn helper() -> String {
    format!(
        r#"// auto-generated by cargo-aiv
fn any_bounded_vec<T: kani::Arbitrary>(bound: usize) -> Vec<T> {{
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<T> = Vec::with_capacity(len);
    for _ in 0..len {{ v.push(kani::any()); }}
    v
}}
fn any_bounded_vec_ranged(bound: usize) -> Vec<i32> {{
    let len: usize = kani::any();
    kani::assume(len <= bound);
    let mut v: Vec<i32> = Vec::with_capacity(len);
    for _ in 0..len {{ let x: i32 = kani::any(); kani::assume(x >= -{RANGE} && x <= {RANGE}); v.push(x); }}
    v
}}"#
    )
}

fn path_head(ty: &syn::Type) -> Option<(String, Vec<syn::Type>)> {
    if let syn::Type::Path(tp) = ty {
        if let Some(seg) = tp.path.segments.last() {
            let mut args = Vec::new();
            if let syn::PathArguments::AngleBracketed(ab) = &seg.arguments {
                for a in &ab.args {
                    if let syn::GenericArgument::Type(t) = a {
                        args.push(t.clone());
                    }
                }
            }
            return Some((seg.ident.to_string(), args));
        }
    }
    None
}

fn scalar_int(ty: &syn::Type) -> Option<String> {
    let (base, args) = path_head(ty)?;
    (args.is_empty() && SCALARS.contains(&base.as_str())).then_some(base)
}

fn map_input(name: &str, ty: &syn::Type, realistic: bool) -> Option<String> {
    if let Some(s) = scalar_int(ty) {
        let mut line = format!("    let {name}: {s} = kani::any();");
        if realistic && s.starts_with('i') {
            line += &format!("\n    kani::assume({name} >= -{RANGE} && {name} <= {RANGE});");
        } else if realistic && s.starts_with('u') {
            line += &format!("\n    kani::assume({name} <= {RANGE});");
        }
        return Some(line);
    }
    let (base, args) = path_head(ty)?;
    match (base.as_str(), args.as_slice()) {
        ("Vec", [inner]) => {
            let et = scalar_int(inner)?;
            if realistic && et == "i32" {
                Some(format!("    let {name}: Vec<i32> = any_bounded_vec_ranged({BOUND});"))
            } else {
                Some(format!("    let {name}: Vec<{et}> = any_bounded_vec::<{et}>({BOUND});"))
            }
        }
        ("Option", [inner]) => {
            scalar_int(inner)?;
            let tystr = quote!(#ty).to_string().replace(' ', "");
            Some(format!("    let {name}: {tystr} = kani::any();"))
        }
        _ => None,
    }
}

/// Build the full lib.rs (helper + fn + harness) for one mode. Err(msg) if unsupported.
fn build(src: &str, realistic: bool) -> Result<(String, String), String> {
    let file = syn::parse_file(src).map_err(|e| format!("parse error: {e}"))?;
    let func = file
        .items
        .iter()
        .find_map(|it| if let syn::Item::Fn(f) = it { Some(f) } else { None })
        .ok_or("no top-level function found")?;
    let name = func.sig.ident.to_string();
    let mut inputs = Vec::new();
    let mut args = Vec::new();
    for arg in &func.sig.inputs {
        if let syn::FnArg::Typed(pt) = arg {
            let pname = match &*pt.pat {
                syn::Pat::Ident(pi) => pi.ident.to_string(),
                _ => return Err(format!("unsupported parameter pattern in `{name}`")),
            };
            let line = map_input(&pname, &pt.ty, realistic).ok_or_else(|| {
                format!("`{name}` param `{pname}: {}` unsupported (v0: scalar ints, Vec<int>, Option<int>)", quote!(#pt).to_string())
            })?;
            inputs.push(line);
            args.push(pname);
        }
    }
    let lib = format!(
        "{}\n\n{}\n\n#[kani::proof]\n#[kani::unwind({UNWIND})]\nfn verify_{name}() {{\n{}\n    let _ = {name}({});\n}}\n",
        helper(),
        src.trim(),
        inputs.join("\n"),
        args.join(", "),
    );
    Ok((name, lib))
}

fn run_kani(dir: &PathBuf, name: &str, lib: &str) -> BTreeMap<String, (bool, Vec<String>)> {
    fs::create_dir_all(dir.join("src")).ok();
    fs::write(
        dir.join("Cargo.toml"),
        format!("[package]\nname = \"aiv_{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\n"),
    )
    .ok();
    fs::write(dir.join("src/lib.rs"), lib).ok();
    let out = Command::new("cargo").arg("kani").current_dir(dir).output();
    let text = match out {
        Ok(o) => String::from_utf8_lossy(&o.stdout).to_string() + &String::from_utf8_lossy(&o.stderr),
        Err(_) => String::new(),
    };
    let mut res = BTreeMap::new();
    let mut cur = String::new();
    for ln in text.lines() {
        if let Some(i) = ln.find("Checking harness verify_") {
            cur = ln[i + "Checking harness verify_".len()..]
                .split(['.', ' '])
                .next()
                .unwrap_or("")
                .to_string();
            res.insert(cur.clone(), (false, Vec::new()));
        } else if !cur.is_empty() && ln.contains("Failed Checks:") {
            if let Some(e) = res.get_mut(&cur) {
                e.1.push(ln.split("Failed Checks:").nth(1).unwrap_or("").trim().to_string());
            }
        } else if !cur.is_empty() && ln.contains("VERIFICATION:-") {
            if let Some(e) = res.get_mut(&cur) {
                e.0 = ln.contains("FAILED");
            }
        }
    }
    res
}

fn main() {
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    if args.first().map(|s| s.as_str()) == Some("aiv") {
        args.remove(0); // invoked as `cargo aiv ...`
    }
    let emit = args.iter().any(|a| a == "--emit");
    let file = match args.iter().find(|a| !a.starts_with("--")) {
        Some(f) => f.clone(),
        None => {
            eprintln!("usage: cargo-aiv [--emit] <file.rs>");
            std::process::exit(2);
        }
    };
    let src = fs::read_to_string(&file).unwrap_or_else(|e| {
        eprintln!("cannot read {file}: {e}");
        std::process::exit(2);
    });

    if emit {
        match build(&src, false) {
            Ok((_, lib)) => println!("{lib}"),
            Err(e) => {
                eprintln!("cargo-aiv: {e}");
                std::process::exit(1);
            }
        }
        return;
    }

    // Verify: strict + realistic, then classify.
    let (name, strict_lib) = match build(&src, false) {
        Ok(v) => v,
        Err(e) => {
            println!("{Y}⏭  cargo-aiv: {e}{X}");
            std::process::exit(1);
        }
    };
    let (_, real_lib) = build(&src, true).unwrap();
    println!("{DIM}verifying `{name}` (strict + realistic bounded model checking)…{X}");
    let base = std::env::temp_dir().join(format!("cargo-aiv-{name}"));
    let strict = run_kani(&base.join("strict"), &name, &strict_lib);
    let real = run_kani(&base.join("realistic"), &name, &real_lib);

    let s = strict.get(&name).cloned().unwrap_or((false, vec![]));
    let r = real.get(&name).cloned().unwrap_or((false, vec![]));
    println!();
    let code = if !s.0 {
        println!("{G}{B}✅ VERIFIED{X}  `{name}` — panic-free for Vec≤{BOUND}, |val|≤{RANGE}.");
        0
    } else if r.0 {
        println!("{R}{B}🔴 BUG{X}  `{name}` — panic reachable on ordinary input:");
        for c in &r.1 {
            println!("     {R}• {c}{X}");
        }
        1
    } else {
        println!("{Y}{B}🟡 UNGUARDED{X}  `{name}` — safe on normal input, but overflows at i32::MAX/MIN:");
        for c in &s.1 {
            println!("     {Y}• {c}{X}");
        }
        println!("     {DIM}add a bounds guard or use checked_/saturating_ arithmetic.{X}");
        0
    };
    std::process::exit(code);
}
